docker-system-prune:
  environment:
    EXCLUDE_CONTAINERS: data
    EXCLUDE_IMAGES: busybox alpine
  image: flaccid/docker-system-prune-crond
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  labels:
      io.rancher.scheduler.global: 'true'
  tty: true
  stdin_open: true
